services:
  chatbot-ia:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "955:5000"
      - "956:11434"
    volumes:
      - ./app:/app/app
      - ./docs:/app/docs  # Importante: montar carpeta docs
      - ./chroma_db:/app/chroma_db  # Persistir base de datos de vectores
      - ./vendor:/app/vendor
      - ./logs:/var/log/chatbot
    environment:
      - FLASK_ENV=production
      - PHP_API_URL=http://localhost:8000/api.php
      - OLLAMA_URL=http://host.docker.internal:11434 #http://ollama:11434
      - IS_SERVER=true
      - SERVER_IP=200.7.106.68
      - PUBLIC_URL=http://200.7.106.68:955
      - OLLAMA_MODEL=phi3:mini
      - DOCS_DIR=/app/docs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped